### ISSUE TITLE
Adaptations to bdv-10.4.1

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/bigdataviewer-playground-display#4]
Branch:
https://github.com/BIOP/bigdataviewer-playground-display/tree/bdv-10.4.1

Essentially ( in a test ):

```
\src\test\java\sc\fiji\bdvpg\projectors\test\DefaultProjectorFactory.java:34:18
java: constructor AccumulateProjectorARGB in class bdv.viewer.render.AccumulateProjectorARGB cannot be applied to given types;
  required: no arguments
  found: java.util.List<bdv.viewer.render.VolatileProjector>,java.util.List<capture#1 of ? extends net.imglib2.RandomAccessible<? extends net.imglib2.type.numeric.ARGBType>>,net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.ARGBType>,int,java.util.concurrent.ExecutorService
  reason: actual and formal argument lists differ in length
```

and deprecated super calls, for instance:

![image](https://user-images.githubusercontent.com/20223054/176285891-863fc7f2-30d0-4f5d-847b-07149a56ed47.png)

**Comment by tpietzsch** [comment]
> Essentially ( in a test ):
> 
> ```
> \src\test\java\sc\fiji\bdvpg\projectors\test\DefaultProjectorFactory.java:34:18
> java: constructor AccumulateProjectorARGB in class bdv.viewer.render.AccumulateProjectorARGB cannot be applied to given types;
>   required: no arguments
>   found: java.util.List<bdv.viewer.render.VolatileProjector>,java.util.List<capture#1 of ? extends net.imglib2.RandomAccessible<? extends net.imglib2.type.numeric.ARGBType>>,net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.ARGBType>,int,java.util.concurrent.ExecutorService
>   reason: actual and formal argument lists differ in length
> ```

That should be resolved by https://github.com/bigdataviewer/bigdataviewer-playground/issues/257#issuecomment-1169248825

**Comment by tpietzsch** [comment]
> and deprecated super calls, for instance:
> 
> ![image](https://user-images.githubusercontent.com/20223054/176285891-863fc7f2-30d0-4f5d-847b-07149a56ed47.png)

The `numThreads` and `executorService` arguments are not required anymore, because parallelization is handled differently now. The deprecated `super` constructor just swallos those arguments and calls the non-deprecated constructor which doesn't have these arguments anymore.

**Comment by NicoKiaru** [comment]
Do you know what's the best way to fix the deprecation in https://github.com/BIOP/bigdataviewer-biop-tools/blob/6b93b23b2cbd01232ba17b6562b3c64bf4b9b483/src/main/java/bdv/util/projector/alpha/LayerAlphaProjectorFactory.java ?

I'm a bit confused, because I can get rid of the executor and of the numthreads in the super call, but then what's the point of having them in the `AccumulateProjectorFactory` interface ?

**Comment by tpietzsch** [comment]
> I'm a bit confused, because I can get rid of the executor and of the numthreads in the super call, but then what's the point of having them in the `AccumulateProjectorFactory` interface ?

Good point :-)
The `numThreads`, `executorService` should be removed from the `AccumulateProjectorFactory` interface as well

**Comment by NicoKiaru** [comment]
Closing - no issue left here. It works well with bdv10.4.1
